Login/urls.py
from django.urls import path, include
from . import views

app_name='App_Login'

urlpatterns = [
    path("login/", views.login_index,name='login'),
    path("signup/", views.sign_index,name='signup'),
    path("logout/", views.logout_user,name='logout'),
    path("profile/<id>/", views.myprofile,name='profile'),
    path("edit_profile/<id>/", views.edit_profile,name='edit_profile'),
    path('follow/<id>',views.follow,name='follow'),
    path('unfollow/<id>',views.unfollow,name='unfollow'),
]

Main/urls.py
from django.urls import path, include
from . import views

app_name='App_Main'

urlpatterns = [
    path("", views.home_index,name='home'),
    path("explore/", views.explore_view,name='explore'),
    path("add_post/", views.add_Post,name='add_post'),
    path("like/<id>/", views.liked,name='like'),
    path("unlike/<id>/", views.unliked,name='unlike'),
]

insta_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login.urls')),
    path('', include('Main.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/Profile/EditProfile.html
{% extends 'Base.html' %} {% load static %} 
{% load crispy_forms_tags %}
{% block css_block %} .gallery-img {
    border-radius: 5px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); cursor:pointer;
    width:300px; height:300px; } .gallery-item { margin-bottom: 15px; }
    .gallery-img:hover { transform: scale(1.05); transition: transform 0.3s
    ease-in-out; } {% endblock css_block %} {% block body_block %}


<h1>Edit Profile</h1>
<div class='container'>
    <div style="width:70%;margin:auto;">
        <form method="POST" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
        <input type="submit" value="Update" class='btn btn-info btn-lg mt-3' style="width: 100%;">  
        
        </form>

    </div>
</div>

    {% endblock body_block %}

templates/Profile/Profile.html
{% extends 'Base.html' %} {% load static %} {% block css_block %} .gallery-img {
border-radius: 5px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); cursor:pointer;
width:300px; height:300px; } .gallery-item { margin-bottom: 15px; }
.gallery-img:hover { transform: scale(1.05); transition: transform 0.3s
ease-in-out; } {% endblock css_block %} {% block body_block %}

<div class="container" style="margin: auto; width: 80%; margin-top: 45px">
  <div class="row">
    <div class="col-5 align-self-center" style="text-align: end">
      <img src="{{profile.profile_pic.url}}" height="150" width="150" style="
          border-radius: 50%;
          border: 1px solid darkgrey;
          margin-right: 20px;
        " />
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex flex-column">
        <h5 style="margin-top: 10px">{{profile.user.username}}</h5>
        <div class="d-flex">
          <p style="margin-right: 14px">{{post_count}} Posts</p>
          <p style="margin-right: 14px">{{followers_count}} followers</p>
          <p style="margin-right: 14px">{{following_count}} following</p>
        </div>
      </div>
      <div class="mt-2">
        <p style="margin-bottom: 0">{{profile.full_name}}</p>
        <pre style="margin-bottom: 0">{{profile.bio}}</pre>
        <p style="margin-bottom: 0">{{profile.website}}</p>
        <p style="margin-bottom: 0">Followed By : another user</p>
      </div>
      {% if my_profile %}
      <a href="{% url 'App_Login:edit_profile' profile.user.id %}" class="btn btn-primary mt-3">Edit Profile</a>

      {% else %}
      {% if already_followed %}
      <a href="{% url 'App_Login:unfollow' profile.user.id %}" class="btn btn-primary mt-3">Following</a>
      {%endif%}
      {% if not already_followed %}

      <a href="{% url 'App_Login:follow' profile.user.id %}" class="btn btn-primary mt-3">Follow</a>
      {% endif %}
      {% endif %}
    </div>
  </div>
  <hr />

  {% if not already_followed and profile.is_private %}
  <div style="margin: auto; margin-top: 20px">
    <div class="row">
      <div class="col align-self-center" style="text-align: end">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-lock"
          viewBox="2 2 12 12" style="border: 2px solid black; border-radius: 50%; padding: 5px">
          <path
            d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2M5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1" />
        </svg>
      </div>
      <div class="col align-self-center">
        <div class="d-flex flex-column">
          <p style="margin-bottom: 0">This account is private</p>
          <p style="margin-bottom: 0" s>
            Follow to see their photos and videos.
          </p>
          <button type="button" class="btn btn-primary mt-3" style="width: 30%">
            Follow
          </button>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row g-4 my-5">
    {% for post in posts %} 
    {% if post.featured_image %}
    <div class="col-sm-6 gallery-item">
      <img src="{{ post.featured_image.image.url }}" class="gallery-img" loading="lazy" data-bs-toggle="modal"
        data-bs-target="#carouselModal{{ post.id }}" />
        <p style="margin-top:20px;">{{post.caption}}</p>
        <p style="margin-top:20px;">{{post.like_count}} Likes {{post.comment_count}} Comments</p>

    </div>
    {% endif %}
  <!-- End of Row -->
    <div class="modal fade" id="carouselModal{{ post.id }}" tabindex="-1" aria-labelledby="carouselModalLabel{{ post.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-sm-6">
              <div id="carousel{{ post.id }}" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  {% for image in post.images.all %}
                  <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img src="{{ image.image.url }}" class="d-block" alt="Image {{ image.id }}"
                      style="width: 100%; height: 450px; object-fit: contain" />
                  </div>
                  {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{ post.id }}"
                  data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carousel{{ post.id }}"
                  data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>
            <div class="col-sm-6" style="height:400px;overflow-y:scroll;">
              <p>{{post.caption}}</p>
              {% for comment in post.post_comment.all %}
              <div style="display:flex;align-items:center;margin-bottom:15px;">
                <div>
                  <img src="{{ comment.user.profile_pic.url }}" width='35' height='35' class="rounded-circle me-2" />
                </div>
                <div style="margin-left:6px;">
                  <strong style="margin-bottom:4px;">{{comment.user.user.username}}</strong>
                  <p style="margin-bottom:4px;">{{comment.text}}</p>
                </div>
              </div>
              {% empty %}
              <!-- Content when there are no posts -->
              <p style="text-align:center;margin:5px 0;">No Comments yet at this post.</p>
              {% endfor %}
              <form method="POST">
                <div class="input-group my-4">
                  {% csrf_token %}{{ form1.text }}
                  <input type="hidden" name="post_id" value="{{ post.id }}">
                  <button type="submit" name="comment" class="btn btn-outline-secondary" 
                    >Comment</button
                  >
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>


  {% empty %}
    <!-- Content when there are no posts -->
    <h4 style="text-align:center;margin:15px 0;">No posts available at the moment.</h4>
  </div>
  {% endfor %}
</div>
    {%endif%}
  </div>


</div>
{% endblock body_block %}